CREATE TABLE IF NOT EXISTS remote_configs (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    value JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE players DROP COLUMN IF EXISTS spins;
ALTER TABLE players DROP COLUMN IF EXISTS gold_spins;
ALTER TABLE players ADD COLUMN IF NOT EXISTS mini_games JSONB NOT NULL DEFAULT '{}';

CREATE INDEX idx_remote_configs_name ON remote_configs(name);
