DROP TABLE IF EXISTS remote_configs;
ALTER TABLE players DROP COLUMN IF EXISTS slots;
ALTER TABLE players DROP COLUMN IF EXISTS mini_games;

ALTER TABLE players ADD COLUMN IF NOT EXISTS spins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN IF NOT EXISTS gold_spins INTEGER NOT NULL DEFAULT 0;